---
title: "Get info for all studies in dbGaP"
output: html_notebook
---

```{r}
source("fetch_dbgap_info.R")
```

```{r}
N <- 3809 # https://ftp.ncbi.nlm.nih.gov/dbgap/studies/
start <- 3801
end <- N
for (start in seq(1, 3701, 100)) {
    end <- start+100-1
    phs <- paste0("phs", stringr::str_pad(start:end, width=6, side="left", pad="0"))
    dat <- lapply(phs, function(x) {
        tmp <- fetch_study_xml(x)
        study <- xml_find_first(tmp, "Study")
        if (is.na(study)) return(NULL)
        date <- xml_release_date(tmp, version=1)
        latest_date <- xml_release_date(tmp, version=NULL)
        cons <- tmp %>%
            xml_consent() %>%
            select(-DUL) %>%
            filter(consent_code != "EA") %>%
            mutate(phs=x)
        info <- tmp %>%
            xml_info() %>%
            select(-accession) %>%
            mutate(parent=as.character(parent)) %>%
            mutate(phs=x)
        part <- xml_partners(tmp) %>%
            arrange(trusted_partner) %>%
            unlist(use.names=FALSE) %>%
            paste(collapse=", ")
        gsr <- xml_gsr(tmp) %>%
            paste(collapse=", ")
        vers <- xml_version(tmp) %>%
            mutate(phs=x)
        dars <- tryCatch({
            count_dars(x, v=vers$version, p=vers$participant_set)
        }, error=function(e) {
            message(x, ": error in fetching DARs")
            return(NA)
        })
        cons %>%
            left_join(info, by="phs") %>%
            left_join(vers, by="phs") %>%
            mutate(first_release_date = date,
                   latest_release_date = latest_date,
                   #num_DARs = dars,
                   trusted_partner = part,
                   GSR = gsr) %>%
            relocate(phs, version, participant_set)
    }) %>%
        bind_rows()
    saveRDS(dat, file=paste0("dbGaP_study_consent_", start, ".rds"))
}
```

```{r}
files <- list.files(pattern="dbGaP_study_consent_")
dat <- lapply(files, readRDS) %>% 
    bind_rows() %>%
    arrange(phs)
saveRDS(dat, "dbGaP_study_consent.rds")
write_tsv(dat, "dbGaP_study_consent.txt", na="")
```
